# **2D array**

In [27]:
import numpy as np

In [28]:
arr_0=np.array([[1,2,3],[4,5,6]])
arr_0


array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
print(arr_0)

[[1 2 3]
 [4 5 6]]


In [30]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- when the value is missing we write np.nan

In [31]:
np.array([[1,2],[4,np.nan]])

array([[ 1.,  2.],
       [ 4., nan]])

In [32]:
arr_1=np.array([[1,2,3],[4,5,6],[7,8,9]] ,dtype=float)

In [33]:
np.array([1,2,3,4,5,0],dtype=bool)

array([ True,  True,  True,  True,  True, False])

In [34]:
arr_1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [35]:
arr_1.ndim

2

In [36]:
arr_1.shape

(3, 3)

**special case one row and 3 col**

In [37]:
arr_3=np.array([1,2,3])
arr_3

array([1, 2, 3])

In [38]:
arr_3.ndim

1

In [39]:
arr_3.shape

(3,)

In [40]:
arr_4=np.array([[1,2,3],])
arr_4

array([[1, 2, 3]])

In [41]:
arr_4.ndim

2

In [42]:
arr_4.shape

(1, 3)

**3D array**

In [43]:
np.zeros((6,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [44]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
np.ones((3,3))+1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

# **identity matrix**
- **Syntax**: np.eye((shape),dtype)

In [47]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.eye(3,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

# **diagonal matrix**
- Extract a diagonal or construct a diagonal array.



In [49]:
np.diag()

TypeError: diag() missing 1 required positional argument: 'v'

In [56]:
arr_5=np.diag([1,2,3])
arr_5

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [57]:
arr_5[0,2]=100
arr_5

array([[  1,   0, 100],
       [  0,   2,   0],
       [  0,   0,   3]])

In [58]:
arr_6=np.array([[1,2],[4,8]])
arr_6

array([[1, 2],
       [4, 8]])

In [59]:
np.diag(arr_6)

array([1, 8])

# **indexing of 2D array**

In [60]:
arr_7=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**extracting row**

In [61]:
arr_7[0]

array([1, 2, 3])

In [62]:
arr_7[9]

IndexError: index 9 is out of bounds for axis 0 with size 3

# **extarcting single value from 2D array**
- **Syntax**: arr_name[row_index,col_index]

In [50]:
arr_7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
print(arr_7[0,0])

1


In [52]:
arr_7[2,2]

np.int64(9)

In [53]:
arr_7[-1]

array([7, 8, 9])

# **to extract multiple rows**
- **Syntax**: arr[star:end]

In [54]:
arr_7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr_7[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

 # **replace a single value in 2D array**

In [63]:
arr_8=np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

In [64]:
arr_8

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [66]:
arr_8[2,2]

np.int64(90)

In [67]:
arr_8[2,2]=1000

In [68]:
arr_8

array([[  10,   20,   30],
       [  40,   50,   60],
       [  70,   80, 1000]])

# **replacing row**

In [69]:
arr_8

array([[  10,   20,   30],
       [  40,   50,   60],
       [  70,   80, 1000]])

In [70]:
arr_8[1]

array([40, 50, 60])

In [71]:
arr_8[1]=[99,78,390]
arr_8

array([[  10,   20,   30],
       [  99,   78,  390],
       [  70,   80, 1000]])

# **flattening**: converting nd array to 1d array

In [72]:
arr_9=np.array([[0,1,2],[3,4,5]])
arr_9

array([[0, 1, 2],
       [3, 4, 5]])

- Return a contiguous flattened array.

A 1-D array, containing the elements of the input, is returned.  A copy is
made only if needed.

In [74]:
arr_10=arr_9.ravel(  )
arr_10

array([0, 1, 2, 3, 4, 5])

In [75]:
np.ravel(arr_9)

array([0, 1, 2, 3, 4, 5])

In [76]:
help(np.ravel)

Help on _ArrayFunctionDispatcher in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.

    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.

    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)

    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional

        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
        slowe

# **Reshape array**

In [85]:
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
     

In [77]:
arr_11=np.arange(6)
print(arr_11)
print(arr_11.shape)

[0 1 2 3 4 5]
(6,)


In [78]:
np.shape(arr_11)

(6,)

In [79]:
arr_11

array([0, 1, 2, 3, 4, 5])

In [80]:
arr_11.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
arr_11.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [84]:
arr_11.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [88]:
arr_12=np.linspace(1,10,9)
arr_12

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [93]:
reshape(arr_12,[3,3])

NameError: name 'reshape' is not defined

In [94]:
arr_12

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [95]:
arr_12.reshape(9,1)

array([[ 1.   ],
       [ 2.125],
       [ 3.25 ],
       [ 4.375],
       [ 5.5  ],
       [ 6.625],
       [ 7.75 ],
       [ 8.875],
       [10.   ]])

# **Transpose**

In [101]:
arr_13=np.arange(12).reshape(3,4)
arr_13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
arr_13.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# **Sorting**
- Sorting along an axis axis=1 ----> row and axis=0----->col

In [105]:
a=np.array([[5,4,6],[2,8,2],[8,9,20]])
print(a)
b=np.sort(a,axis=0)

[[ 5  4  6]
 [ 2  8  2]
 [ 8  9 20]]


In [106]:
print(b) # ------> sorted colwise

[[ 2  4  2]
 [ 5  8  6]
 [ 8  9 20]]


In [108]:
np.sort(a,axis=1)

array([[ 4,  5,  6],
       [ 2,  2,  8],
       [ 8,  9, 20]])

In [110]:
a

array([[ 5,  4,  6],
       [ 2,  8,  2],
       [ 8,  9, 20]])

# -----> when axis is not specified the it is row wise sorting

In [109]:
np.sort(a) # rowwise sorting

array([[ 4,  5,  6],
       [ 2,  2,  8],
       [ 8,  9, 20]])

# **Mathametical operations on 2d array**

In [112]:
a=np.array([[1,2],[3,4],[5,6]])

print(a)


[[1 2]
 [3 4]
 [5 6]]


In [113]:
b=np.array([[40,7],[14,30],[35,88]])
print(b)

[[40  7]
 [14 30]
 [35 88]]


- elementwise addition

In [114]:
a+b

array([[41,  9],
       [17, 34],
       [40, 94]])

# **dot product**
- elementwise mutiplication

In [117]:
a*b

array([[ 40,  14],
       [ 42, 120],
       [175, 528]])

# matrix multiplication cross product

In [122]:
a=np.linspace(10,99,9).reshape(3,3)
a

array([[10.   , 21.125, 32.25 ],
       [43.375, 54.5  , 65.625],
       [76.75 , 87.875, 99.   ]])

In [125]:
b=np.linspace(77,99,9).reshape(3,3)
b

array([[77.  , 79.75, 82.5 ],
       [85.25, 88.  , 90.75],
       [93.5 , 96.25, 99.  ]])

In [127]:
np.matmul(a,b)

array([[ 5586.28125,  5760.5625 ,  5934.84375],
       [14121.9375 , 14571.5625 , 15021.1875 ],
       [22657.59375, 23382.5625 , 24107.53125]])

In [128]:
a=np.array([[1,90],[22,76]])
# b=np.array([[737,828],[320,np.nan]])
a


array([[ 1, 90],
       [22, 76]])

In [129]:
b=np.array([[737,828],[320,np.nan]])
b

array([[737., 828.],
       [320.,  nan]])

# **concatenation**

In [131]:
a

array([[ 1, 90],
       [22, 76]])

In [132]:
b

array([[737., 828.],
       [320.,  nan]])

- **Syntax**: concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )

In [138]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )

    Join a sequence of arrays along an existing axis.

    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.20.0

    c

In [139]:
a,b

(array([[ 1, 90],
        [22, 76]]),
 array([[737., 828.],
        [320.,  nan]]))

In [140]:
np.concatenate((a,b),axis=0)

array([[  1.,  90.],
       [ 22.,  76.],
       [737., 828.],
       [320.,  nan]])

In [141]:
np.concatenate((a,b),axis=1)

array([[  1.,  90., 737., 828.],
       [ 22.,  76., 320.,  nan]])

# **Horizontal stack**
- stack(tup, *, dtype=None, casting='same_kind')
- Stack arrays in sequence horizontally (column wise).

In [146]:
help(np.hstack)

Help on _ArrayFunctionDispatcher in module numpy:

hstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence horizontally (column wise).

    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.

    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.

    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.

    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.24

    c

In [144]:
np.hstack((a,b))

array([[  1.,  90., 737., 828.],
       [ 22.,  76., 320.,  nan]])

# **vertical stack**


- vstack(tup, *, dtype=None, casting='same_kind')
- Stack arrays in sequence vertically (row wise).


In [148]:
help(np.vstack)

Help on _ArrayFunctionDispatcher in module numpy:

vstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence vertically (row wise).

    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.

    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.

    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.

    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.24

    casting : {'no',