**0Darray**

In [123]:
a=45
print(a)
print(type(a))

45
<class 'int'>


# importing numpy

In [124]:
import numpy as np

In [125]:
arr_0=np.array(a)
print(f"arr_0: {arr_0}")
print(f"type(arr_0): {type(arr_0)}")

arr_0: 45
type(arr_0): <class 'numpy.ndarray'>


**ndim  of 0D array**
- ndim will give the dimention of the array

In [126]:
print(f"ndim: {arr_0.ndim}")

ndim: 0


**0d shape**
- 0d array has shape as ()
- ndim = len   (shape)

In [127]:
print(f"shape: {arr_0.shape}")

shape: ()


In [128]:
b="string"
arr_1=np.array(b)
print(f"arr_1: {arr_1}")
print(f"type: {type(arr_1)}")

arr_1: string
type: <class 'numpy.ndarray'>


In [129]:
arr_1

array('string', dtype='<U6')

In [130]:
print(arr_1)

string


**1D array**

In [131]:
a=[1,2,3,4]
print(a)
print(type(a))

[1, 2, 3, 4]
<class 'list'>


In [132]:
arr_2=np.array(a)
print(f"arr_2 : {arr_2}")
print(f"type: {type(arr_2)}")

arr_2 : [1 2 3 4]
type: <class 'numpy.ndarray'>


**1D shape**
- shape :(no of items  , )

In [133]:
arr_2.shape

(4,)

**1D ndim**

In [134]:
arr_2.ndim

1

**function for creating 1D arry**

In [135]:
arr_2

array([1, 2, 3, 4])

#np.ndim(array) = = len(np.shape(array))

In [136]:
np.ndim(arr_2)==len(np.shape(arr_2))

True

# **functions for creating 1D array**

# **arange**

- arange is an array-value version of the build in python range function
- **Syntax:** np.array(Start,end,step)
- end value will be excluded

In [137]:
arr_3=np.arange(1,10)
arr_3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
print(arr_3)

[1 2 3 4 5 6 7 8 9]


In [139]:
arr_4=np.arange(10)
arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **linspace**
- return evenly spaced  numbers over a specified interval
- **Sytax**: np.linspace(Start,end  , number_of_ samples)
- formula :   (end-start)/(n-1)
- both start and end are included

In [140]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [141]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

- default sample number is 50

In [142]:
len(np.linspace(1,10))

50

In [143]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [144]:
np.linspace(-1,10,10)

array([-1.        ,  0.22222222,  1.44444444,  2.66666667,  3.88888889,
        5.11111111,  6.33333333,  7.55555556,  8.77777778, 10.        ])

# **zeros**
- **Syntax**: zeros(shape, dtype=float, order='C', *, like=None)
- it will return the array in the given shape
- here in place of shape you can pass tuple or int


In [145]:
np.zeros( 10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [146]:
np.zeros((4,),dtype=int)

array([0, 0, 0, 0])

# **ones**
- generate a array of ones
- **Systax** np.ones(shape)

In [147]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [148]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [149]:
np.ones((10),dtype=str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [150]:
np.ones(7,dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True])

# **random.randint**
-  Return random integer in range [a, b], including start but  end points is exluded.

- **Syntax**: np.random.randint(start,end, no_of_samples)

In [151]:
# importing random module
import random
# i want 5 random number
a=[]
for i in range(5):
    a.append(random.randint(1,6))
print(a)

[4, 1, 2, 1, 5]


In [152]:
np.random.randint( 1,5,10)

array([4, 2, 2, 4, 4, 3, 4, 3, 4, 2])

In [153]:
def random_randint(start_val, end_val, num_samples):
  import random
  l=[]
  for _ in range(num_samples):
    y=random.randint(start_val, end_val)
    l.append(y)
  a=np.array(l)
  return a

# **Backend code**
- this is the backendcode of np.random.randint

In [154]:
def random_randint(star,end,number_of_samples):
    l=[]
    for i in range(number_of_samples):
       l.append(random.randint(star,end))
    a=np.array(l)
    return a




In [155]:
random_randint(1,5,10)

array([1, 2, 2, 5, 5, 5, 2, 3, 2, 2])

# **convert array to list**
- array.tolist()

In [156]:
n=np.arange(7)
n

array([0, 1, 2, 3, 4, 5, 6])

In [157]:
n.tolist()

[0, 1, 2, 3, 4, 5, 6]

# **ACCESSING A SINGLE VALUE THROUGH INDEXING**

In [158]:
n1=np.arange(10,90,10)
n1

array([10, 20, 30, 40, 50, 60, 70, 80])

 # **Accessing a single value through indexing**

In [159]:
# indexing

n1[1]

np.int64(20)

In [160]:
n1[7]

np.int64(80)

In [161]:
n1[-3]

np.int64(60)

# **Accessing multiple elements by slicing**

In [162]:
n1

array([10, 20, 30, 40, 50, 60, 70, 80])

In [163]:
n1[0:5]

array([10, 20, 30, 40, 50])

In [164]:
n1[0:5:2]

array([10, 30, 50])

# **accessing a multiple values based on indexing**

In [165]:
n1

array([10, 20, 30, 40, 50, 60, 70, 80])

**backend code**

In [166]:
# getting values which is not having proper pattern
l=[]
for i in [1,5,6,7]:
  l.append(n1[i])
print(np.array(l))


[20 60 70 80]


In [167]:
n1

array([10, 20, 30, 40, 50, 60, 70, 80])

- to extarct multiple values from array
- **Syntax :**  array[list of indexes]

In [168]:
n1[[1,2,0,0]] # --------> here all these are indexes

array([20, 30, 10, 10])

# **Accesing a multiple values based on condition [mask indexing  or fancy indexing ]**
- **Syntax** array[condition]
- first  it will check condition , the items which satisfies the condition , tat item will be select  

In [169]:
s=np.array([45,46,47,48])
s

array([45, 46, 47, 48])

- to get the boolean condition

In [170]:
s>45

array([False,  True,  True,  True])

**backend code**

In [171]:
l=[]
for i in s:
  l.append( i>45)
np.array(l)


array([False,  True,  True,  True])

-  to  get data based on  condition
- array[condition]

In [172]:
s

array([45, 46, 47, 48])

In [173]:
s[s>47]

array([48])

**backend code**

In [174]:
l=[]
for i in s:
  if i>47:
    l.append(i)
np.array(l)

array([48])

# **modify the value in numpy**
- Add a single value in a array
- **syntax** np.append(array,value)

In [175]:
k=np.arange(89,130,8)
k

array([ 89,  97, 105, 113, 121, 129])

In [176]:
a1=np.append(k,9999)
a1

array([  89,   97,  105,  113,  121,  129, 9999])

In [177]:
k


array([ 89,  97, 105, 113, 121, 129])

# ** adding multiple value**
- **Syntax** np.append(list of element)

In [178]:
k

array([ 89,  97, 105, 113, 121, 129])

In [179]:
a2=np.append(k,[9999,"str"])
a2

array(['89', '97', '105', '113', '121', '129', '9999', 'str'],
      dtype='<U21')

# **replacing single value in a 1d array**
- replacing single value  in a 1d array

In [180]:
k

array([ 89,  97, 105, 113, 121, 129])

In [181]:
k[1]=0000000

In [182]:
k

array([ 89,   0, 105, 113, 121, 129])

# **both of them must be replaced with same value**

In [183]:
k

array([ 89,   0, 105, 113, 121, 129])

In [184]:
k[[0,1]]=999999

In [185]:
k

array([999999, 999999,    105,    113,    121,    129])

# **replace a multiple value with multtiple value**

In [186]:
k

array([999999, 999999,    105,    113,    121,    129])

In [187]:
k[[0,1]]=[98.7,99.4]
k

array([ 98,  99, 105, 113, 121, 129])

In [188]:
k[[0,1]]=90,10
k

array([ 90,  10, 105, 113, 121, 129])

# **Delete**
- delete a single value in array
- **Synatx**: np.delete(array,index)

In [189]:
m=np.linspace(10,1000,6)
m

array([  10.,  208.,  406.,  604.,  802., 1000.])

In [190]:
np.delete(m,1)

array([  10.,  406.,  604.,  802., 1000.])

# **delete mutiple index number**
- **Syntax:** np.delete(array,list of index)

In [191]:
m

array([  10.,  208.,  406.,  604.,  802., 1000.])

In [192]:
np.delete(m,[1,0,3])

array([ 406.,  802., 1000.])

# **copy of array**

In [195]:
x1=np.linspace(88,999,5)
x1

array([ 88.  , 315.75, 543.5 , 771.25, 999.  ])

# **shallow copy**

In [197]:
x2=x1.copy()
x2

array([ 88.  , 315.75, 543.5 , 771.25, 999.  ])

In [213]:
x1[1]=10000
print(f"x1: {x1}  \n x2:{x2}")

x1: [   88. 10000.   999. 10000. 10000.]  
 x2:[ 88.   315.75 543.5  771.25 999.  ]


# **sorting array**

In [214]:
x1

array([   88., 10000.,   999., 10000., 10000.])

In [215]:
np.sort(x1)

array([   88.,   999., 10000., 10000., 10000.])

# **Operation**
- Arthimetical operation

In [217]:
v=np.linspace(39,89,7)
v

array([39.        , 47.33333333, 55.66666667, 64.        , 72.33333333,
       80.66666667, 89.        ])

In [218]:
v+10

array([49.        , 57.33333333, 65.66666667, 74.        , 82.33333333,
       90.66666667, 99.        ])

In [219]:
v

array([39.        , 47.33333333, 55.66666667, 64.        , 72.33333333,
       80.66666667, 89.        ])

In [220]:
v*4

array([156.        , 189.33333333, 222.66666667, 256.        ,
       289.33333333, 322.66666667, 356.        ])

In [221]:
v

array([39.        , 47.33333333, 55.66666667, 64.        , 72.33333333,
       80.66666667, 89.        ])

In [222]:
v**4

array([ 2313441.        ,  5019591.30864198,  9602423.71604939,
       16777216.        , 27374986.67901236, 42342495.01234569,
       62742241.        ])

In [223]:
v/4

array([ 9.75      , 11.83333333, 13.91666667, 16.        , 18.08333333,
       20.16666667, 22.25      ])

In [227]:
z1=np.arange(1,6)
z2=np.arange(2,7)
print(f"z1: {z1}  \nz2 :{z2}")

z1: [1 2 3 4 5]  
z2 :[2 3 4 5 6]


In [228]:
z1+z2

array([ 3,  5,  7,  9, 11])

In [229]:
z1-z2

array([-1, -1, -1, -1, -1])

In [230]:
z1*z2

array([ 2,  6, 12, 20, 30])

# **comparison operator**


In [231]:
z1==z2

array([False, False, False, False, False])

In [233]:
z1<z2

array([ True,  True,  True,  True,  True])

- to check entire array

In [234]:
np.array_equal(z1,z2)

False

In [235]:
np.array_equal(z1,z1)

True

**mathematical  operation**

In [236]:
np.log(z1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [237]:
np.exp(z2)

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ,
       403.42879349])